import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent.parent))

correct_words_dict : dict[str,str] = {
    "lefte" : "left",
    "eies" : "eyes",
    "loue" : "love",
    "soule" : "soul",
    "saluation" : "solution",
    "liue" : "live",
    "aliue" : "alive",
    "euery" : "every",
    "soull" : "soul",
    "sicke" : "sick",
    "inuest" : "invest",
    "doe" : "do",
    "harte" : "hart",
    "giuen vp" : "given up",
    "giuen" : "given",
    "vp": "up",
    "voyce" : "voice",
    "goe" : "go",
    "musick" : "music",
    "walke" : "walk",
    "haue" : "have",
    "euer" : "ever",
    "backe" : "back",
    "ouer" : "over", 
    "turne" : "turn",
    "liue for euer" : "live forever",
    "milke" : "milk",
    "necke" : "neck",
    "losse" : "loss",
    "sleepe" : "sleep",
    "iuice" : "juice",
    "clocke" : "clock",
    "finde" : "find",
    "sicke" : "sick",
    "wind" : "wind", 
    "leaue" : "leave",
    "heauen" : "heaven",
    "lesse" : "less",
    "bloud" : "blood",
    "faine" : "fain", 
    "them selues" : "themselves", 
    "lefte" : "left",
    "nere" : "never",
    "here" : "her",
    "owne" : "own",
    "agen" : "again",
    "seruingman" : "servingman",
    "driue" : "drive",
    "bate" : "abate",
    "slaue" : "slave",
    "weare" : "wear",
    "shal" : "shall",
    "fil" : "fill",
    "nailes" : "nails",
    "wil" : "will",
    "pleasāt" : "pleasant",
    "hel" : "hell",
    "laie" : "lay",
    "thy" : "your",
    "vpon" : "upon",
    "fruitfull" : "fruitful",
    "thine" : "your",
    "ryots" : "riots", 
    "heauy" : "heavy",
    "drawes" : "draws",
    "liddes" : "lids",
    "ouer" : "over",
    "dankishe" : "dankish",
    "nowe" : "now",
    "shewed" : "showed",
    "moone" : "moon",
    "mee" : "me",
    "ith" : "in the",
    "wayning" : "waning",
    "ryot" : "riot",
    "iaylor" : "jailor",
    "mony" : "money",
    "vpon" : "upon",
    "saluation" : "salvation",
    "throwes" : "throes",
    "ioynt" : "joint",
    "deuill" : "devil",
    "departes" : "departs",
    "heaues" : "heaves",
    "nailes" : "nails",
    "bloudied" : "bloodied",    
    "lippes" : "lips",
    "laue" : "lave",
    "browes" : "brow",
    "heere" : "here",
    "heauens" : "heavens",
    "selues" : "selves",
    "loues" : "loves",
    "raigne" : "reign",
    "ayre" : "air",
    "vastnes" : "vastness",
    "sailes" : "sails",
    "vs" : "us",
    "haue" : "have",
    "iust" : "just",
    "reuenge" : "revenge",
    "ielly" : "jelly",
    "aire" : "air",
    "betwixt" : "between",   
    "sauour" : "savour",
    "Generall" : "General",
    "hath" : "has",
    "ruffe" : "ruff",
    "necke" : "neck",
    "drowne" : "drown",
    "vertues" : "virtues",
    "egs" : "eggs",
    "heeles" : "heels",
    "asse" : "ass",
    "thou" : "you",
    "luste" : "lust",
    "generall" : "general",
    "stil" : "still",
    "thy" : "your"       
}


def word_correction(src_word):
    if src_word in correct_words_dict.keys(): 
        # print(f"fixed {src_word} -> {correct_words_dict[src_word]}")
        return correct_words_dict[src_word]
    return src_word

def rephrase(fragment):
    for w in fragment.split():
        fragment=fragment.replace(w,word_correction(w))
    return fragment
